// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwgbazhcsjdmjpeaikea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Z2Jhemhjc2pkbWpwZWFpa2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDQ3MTYsImV4cCI6MjA2MjM4MDcxNn0.1yo5YpJhTfv1QHsI3GnQCwVla4yvBPZX7QL67BjF73Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);